// Generated by `npm.cmd run build` through scripts/prepare-vercel-ssr.mjs.
// @ts-expect-error generated at build time
import serverModule from './_dist/server.js';

const server = serverModule.default ?? serverModule;

if (!server?.fetch || typeof server.fetch !== 'function') {
  throw new Error('Could not load TanStack Start server entry from api/_dist/server.js');
}

export default async function handler(request: Request) {
  return server.fetch(request, process.env, undefined);
}
(handler as any).fetch = (request: Request) => server.fetch(request, process.env, undefined);

export const fetch = (request: Request) => server.fetch(request, process.env, undefined);
